services:
  # Official latest AOP Version
  aop:
    image: aop_latest_${AOP_FULL_VERSION}:${DCPAPX_PROJECT_NAME}
    labels:
      - "dockapex_config=${DCPAPX_PROJECT_NAME}"
    build:
      context: ../aop
      args:
        - AOP_FULL_VERSION=${AOP_FULL_VERSION}
    container_name: aop
    ports:
      - 8010:${AOP_PORT}
    restart: unless-stopped
    
    environment:
      - DCPAPX_PROJECT_NAME=${DCPAPX_PROJECT_NAME}
    secrets:
      - oracle_pwd
    
    healthcheck:
      test: curl --fail -s http://localhost:${AOP_PORT}/ || exit 1
      interval: 1m
      timeout: 30s
      retries: 45
      start_period: 5m

    volumes:
      - ${DCKAPX_CONF_FILE}:/opt/oracle/config.env
      - apexofficeprint:/apexofficeprintstartup


# Define some volumes
volumes:
  apexofficeprint:
    driver: local

secrets:
  oracle_pwd:
    environment: DB_PASS    