services:
  # Official latest AOP Version
  aop:
    image: aop_latest:${DCPAPX_PROJECT_NAME}
    labels:
      - "dockapex_config=${DCPAPX_PROJECT_NAME}"
    build:
      context: ../aop
    container_name: aop
    ports:
      - 8010:${AOP_PORT}
    restart: always
    depends_on:
      database:
        condition: service_healthy

    entrypoint:
      - /APEXOfficePrint/APEXOfficePrintLinux64
      - -s
      - /apexofficeprintstartup

    healthcheck:
      test: curl --fail -s http://localhost:${AOP_PORT}/ || exit 1
      interval: 1m
      timeout: 30s
      retries: 45
      start_period: 5m

    volumes:
      - apexofficeprint:/apexofficeprintstartup


# Define some volumes
volumes:
  apexofficeprint:
    driver: local