services:
  apex:
    image: apex_${APEX_FULL_VERSION}:${DCPAPX_PROJECT_NAME}
    labels:
      - "dockapex_config=${DCPAPX_PROJECT_NAME}"
    build:
      context: ../apex
      args:
        - APEX_VERSION=${APEX_VERSION}
        - APEX_FULL_VERSION=${APEX_FULL_VERSION}
        - APEX_URL=${APEX_URL}
        - APEX_PSET_URL=${APEX_PSET_URL}
        - APEX_IMAGE_PREFIX=${APEX_IMAGE_PREFIX}
    environment:
      - DCPAPX_PROJECT_NAME=${DCPAPX_PROJECT_NAME}
    secrets:
      - oracle_pwd
      - smtp_pwd
    container_name: apex
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ${DCKAPX_CONF_FILE}:/opt/oracle/config.env
      - apx_imgs:/opt/oracle/images
      - db_store:/opt/oracle/oradata
    hostname: apex
    healthcheck:
      test: 'cat /opt/oracle/images/apex_version.txt | grep "${APEX_FULL_VERSION}"'
      interval: 1m
      timeout: 30s
      retries: 45
      start_period: 1m

volumes:
  apx_imgs:
    driver: local

secrets:
  oracle_pwd:
    environment: DB_PASS
  smtp_pwd:
    environment: SMTP_PASSWORD