services:
  database:
    container_name: database
    image: container-registry.oracle.com/database/free:latest
    labels:
      - "dockapex_config=${DCPAPX_PROJECT_NAME}"
    ports:
      - 1521:${DB_PORT}
    environment:
      - ORACLE_PASSWORD_FILE=/run/secrets/oracle_pwd
    secrets:
      - oracle_pwd
    volumes:
      - db_store:/opt/oracle/oradata
    hostname: ${DB_HOST}
    restart: unless-stopped

volumes:
  db_store:
    driver: local

secrets:
  oracle_pwd:
    environment: DB_PASS