services:
  database:
    container_name: database
    # image: gvenzl/oracle-xe:21-full
    # image: container-registry.oracle.com/database/express:21.3.0-xe
    image: container-registry.oracle.com/database/free:latest
    labels:
      - "dockapex_config=${DCPAPX_PROJECT_NAME}"
    ports:
      - 1521:${DB_PORT}
    environment:
      - ORACLE_PASSWORD_FILE=/run/secrets/oracle_pwd
      # - ORACLE_PASSWORD=${DB_PASS}
    secrets:
      - oracle_pwd
    volumes:
      - db_store:/opt/oracle/oradata
    hostname: ${DB_HOST}
    healthcheck:
      # test: [ "CMD", "/opt/oracle/healthcheck.sh"]
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 10s
      retries: 45
      start_period: 5m

volumes:
  db_store:
    driver: local

secrets:
  oracle_pwd:
    environment: DB_PASS