services:
  database:
    container_name: database
    image: gvenzl/oracle-xe:21-full
    labels:
      - "dockapex_config=${DCPAPX_PROJECT_NAME}"
    ports:
      - 1521:${DB_PORT}
    environment:
      - ORACLE_PASSWORD_FILE=/run/secrets/db_pwd
      # - ORACLE_PASSWORD=${DB_PASS}
    secrets:
      - db_pwd
    volumes:
      - db_store:/opt/oracle/oradata
    hostname: ${DB_HOST}
    healthcheck:
      test: [ "CMD", "/opt/oracle/healthcheck.sh"]
      interval: 10s
      retries: 45
      start_period: 5m

volumes:
  db_store:
    driver: local

secrets:
  db_pwd:
    environment: DB_PASS